/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package appointments.ui;

/**
 *
 * @author Md Ashiqur Rahman
 */
import appointments.getway.TempDb;

import appointments.models.*;

public class Layout extends javax.swing.JFrame {

    private static TempDb _db;
    /** Creates new form Layout
     * @param tempDb */
    public Layout(TempDb tempDb) {
        _db = tempDb;
        initComponents();
        //panelPatient.setVisible(false);     
        //panelVisitPatient.setVisible(false);

    }
     public Layout(TempDb tempDb, UserModel user) {
        _db = tempDb;
        initComponents();
        panelPatient.setVisible(false);     
        panelVisitPatient.setVisible(false);
        txtUserName.setText(user.userName);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        menuBar3 = new java.awt.MenuBar();
        menu5 = new java.awt.Menu();
        menu6 = new java.awt.Menu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        btnLogout = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnAddPatient = new javax.swing.JButton();
        btnStartVisit = new javax.swing.JButton();
        txtUserName = new javax.swing.JLabel();
        panelDashboard = new appointments.ui.panelDashboard();
        panelPatient = new appointments.ui.PatientPanel(_db);
        panelVisitPatient = new appointments.ui.VisitPatientPanel(_db);

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("jMenu2");

        jMenu5.setText("jMenu5");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        menu5.setLabel("File");
        menuBar3.add(menu5);

        menu6.setLabel("Edit");
        menuBar3.add(menu6);

        jMenu6.setText("jMenu6");

        jMenu7.setText("jMenu7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Appointmet Solution");
        setBackground(new java.awt.Color(0, 153, 102));
        setLocation(new java.awt.Point(150, 50));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setBackground(new java.awt.Color(0, 102, 51));
        btnLogout.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 90, -1));

        btnHome.setBackground(new java.awt.Color(0, 102, 51));
        btnHome.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, -1));

        btnAddPatient.setBackground(new java.awt.Color(0, 102, 51));
        btnAddPatient.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnAddPatient.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPatient.setText("Add Patient");
        btnAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPatientActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 130, -1));

        btnStartVisit.setBackground(new java.awt.Color(0, 102, 51));
        btnStartVisit.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnStartVisit.setForeground(new java.awt.Color(255, 255, 255));
        btnStartVisit.setText("Start Visit");
        btnStartVisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartVisitActionPerformed(evt);
            }
        });
        getContentPane().add(btnStartVisit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 120, -1));

        txtUserName.setBackground(new java.awt.Color(255, 255, 255));
        txtUserName.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(0, 102, 102));
        txtUserName.setText("Welcome ");
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 110, -1));
        getContentPane().add(panelDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));
        getContentPane().add(panelPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 460));
        getContentPane().add(panelVisitPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPatientActionPerformed
        // TODO add your handling code here:
        panelVisitPatient.setVisible(false);
        panelDashboard.setVisible(false);
        panelPatient.setVisible(true);
    }//GEN-LAST:event_btnAddPatientActionPerformed

    private void btnStartVisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartVisitActionPerformed
        // TODO add your handling code here:
        
        panelPatient.setVisible(false);
        panelDashboard.setVisible(false);
        panelVisitPatient.setVisible(true);
    }//GEN-LAST:event_btnStartVisitActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Login(_db);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        panelPatient.setVisible(false);
        panelVisitPatient.setVisible(false);
        panelDashboard.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Layout(_db).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPatient;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnStartVisit;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.Menu menu5;
    private java.awt.Menu menu6;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.MenuBar menuBar3;
    private appointments.ui.panelDashboard panelDashboard;
    private appointments.ui.PatientPanel panelPatient;
    private appointments.ui.VisitPatientPanel panelVisitPatient;
    private javax.swing.JLabel txtUserName;
    // End of variables declaration//GEN-END:variables

}
